[project]
name = "redb"
requires-python = ">=3.7"
dynamic = ["version"]

[build-system]
requires = ["maturin>=0.13.0,<0.14"]
build-backend = "maturin"

[tool.maturin]
compatibility = "manylinux2014"
features = ["python"]
